# Generated by Django 4.1 on 2022-09-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mywatchlist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="rating_movie",
            field=models.CharField(default="0/10", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="watchlist",
            name="release_date",
            field=models.CharField(default="none", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="watchlist",
            name="title_movie",
            field=models.CharField(default="none", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="watchlist",
            name="watched_status",
            field=models.CharField(default="none", max_length=255),
            preserve_default=False,
        ),
    ]
