# Generated by Django 4.1 on 2022-09-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mywatchlist", "0003_alter_watchlist_rating_movie_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="release_date",
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name="watchlist", name="title_movie", field=models.TextField(),
        ),
    ]
