# Generated by Django 4.1 on 2022-09-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mywatchlist", "0004_alter_watchlist_release_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="rating_movie",
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="release_date",
            field=models.CharField(max_length=800),
        ),
    ]
