# Generated by Django 4.1 on 2022-09-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mywatchlist", "0006_alter_watchlist_watched_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="title_movie",
            field=models.CharField(max_length=800),
        ),
    ]
